server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nuc_2023_11_26?serverTimezone=UTC&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
    username: root
